### ISSUE TITLE
ツール自体のウィンドウを選択出来てしまう

### ISSUE THREAD

**Issue by tYoshiyuki** [mikkame/the_wipe#39]
アプリケーションを選択・表示する際に、ツール自体のウィンドウを選択すると表示がおかしくなります。
機能的にツール自体を選択する必要性は無いと思いますので、選択不能にした方が良いかと思いました。

<img src="https://user-images.githubusercontent.com/25566072/81945071-91ff8b00-9638-11ea-84f0-ad82dd1cae4d.jpg" width="320px">

**Comment by mikkame** [comment]
ありがとうございます！
ご指摘のとおりです！
修正します
