### ISSUE TITLE
PDF表示ウィンドウにファイルをドロップするとエラーが発生する

### ISSUE THREAD

**Issue by tYoshiyuki** [mikkame/the_wipe#43]
PDF表示したiframeに対して、PDFファイルをドロップするとJavaScriptエラーが発生します。
Webタブや画面共有タブだと問題無いようです。

<img src="https://user-images.githubusercontent.com/25566072/82123112-88aa2600-97d2-11ea-8984-1112c205b9ad.png" width="320px">

**Comment by mikkame** [comment]
iframeにファイルを入れるとバグる件は把握しており
対応したつもりだったのですがMacでしか検証できておらず・・・。
すみません

**Comment by mikkame** [comment]
PDFJSを導入してiframeを撤廃することで回避しました

**Comment by mikkame** [comment]
v0.1.2-betaで修正済みです
